---
name: Checks

on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
  deploy:
    name: Deploy to production
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/onofreb/Documents/Code/PruebaT
            docker compose down
            docker compose up -d